# Generated by Django 4.2.2 on 2025-01-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='Longitude')),
                ('y', models.FloatField(verbose_name='Latitude')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_gr', models.CharField(max_length=100, null=True, verbose_name='Name (Greek)')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Note')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_gr', models.CharField(max_length=100, null=True, verbose_name='Name (Greek)')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varosha.point')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('source', models.CharField(default='unknown', max_length=64)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_gr', models.CharField(max_length=100, null=True, verbose_name='Name (Greek)')),
                ('caption', models.CharField(max_length=100, null=True, verbose_name='Caption')),
                ('caption_gr', models.CharField(max_length=100, null=True, verbose_name='Caption (Greek)')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='varosha.point')),
            ],
        ),
    ]
