# Generated by Django 4.2.2 on 2024-05-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birth_year', models.CharField(max_length=4)),
                ('death_year', models.CharField(max_length=4)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varosha.point')),
                ('parents', models.ManyToManyField(related_name='children', to='varosha.person')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varosha.point')),
            ],
        ),
    ]
