# Generated by Django 4.2.2 on 2025-01-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='caption_gr',
        ),
        migrations.RemoveField(
            model_name='media',
            name='name_gr',
        ),
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
        migrations.RemoveField(
            model_name='note',
            name='name_gr',
        ),
        migrations.RemoveField(
            model_name='point',
            name='name_gr',
        ),
    ]
