# Generated by Django 4.2.2 on 2024-05-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='media',
            new_name='point',
        ),
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=2),
        ),
    ]
