# Generated by Django 4.2.2 on 2024-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0002_rename_media_media_point_rename_media_person_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Business'), ('O', 'Other')], default='P', max_length=2),
        ),
    ]
