# Generated by Django 4.2.2 on 2025-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0003_remove_media_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
