# Generated by Django 4.2.2 on 2024-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0003_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Business'), ('O', 'Other')], default='P', max_length=2),
        ),
    ]
