# Generated by Django 4.2.2 on 2025-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0005_media_time_added_note_time_added_point_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
