# Generated by Django 4.2.2 on 2024-05-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0005_person_name_gr_point_name_gr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name_gr',
            field=models.CharField(max_length=30, verbose_name='Name in Greek'),
        ),
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Business'), ('O', 'Other')], default='H', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.FloatField(verbose_name='Latitude'),
        ),
    ]
