# Generated by Django 4.2.2 on 2025-01-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0006_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varosha.point'),
        ),
    ]
