# Generated by Django 4.2.2 on 2025-02-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0007_alter_media_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Caption'),
        ),
    ]
