# Generated by Django 4.2.2 on 2024-05-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0010_remove_media_path_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='person',
            name='point',
        ),
    ]
