# Generated by Django 4.2.2 on 2024-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0012_person_father_person_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
