# Generated by Django 4.2.2 on 2024-05-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0014_person_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Link Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='varosha.point')),
            ],
        ),
    ]
