# Generated by Django 4.2.2 on 2024-06-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0015_pointlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('el', 'Greek')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='date',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='media',
            name='description_el',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('advertisement', 'Advertisement'), ('poster', 'Poster'), ('other', 'Other')], default='photo', max_length=32),
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.CharField(choices=[('own/family', 'Own/Family'), ('social media', 'Social Media'), ('unknown', 'Unknown')], default='unknown', max_length=64),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('model', 'Model'), ('user', 'User')], max_length=16)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='varosha.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='varosha.media'),
        ),
    ]
