# Generated by Django 4.2.2 on 2024-06-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0017_conversation_is_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.CharField(default='unknown', max_length=64),
        ),
    ]
