# Generated by Django 4.2.2 on 2024-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0020_person_media_alter_media_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('advertisement', 'Advertisement'), ('poster', 'Poster'), ('video', 'Video'), ('other', 'Other')], default='photo', max_length=32),
        ),
    ]
