# Generated by Django 4.2.2 on 2024-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0022_alter_person_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
