# Generated by Django 4.2.2 on 2024-07-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0023_media_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='varosha.point'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='varosha.media'),
        ),
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.CharField(choices=[('U', 'Under construction'), ('P', 'Pending'), ('A', 'Approved')], default='P', max_length=2, verbose_name='Status'),
        ),
    ]
