# Generated by Django 4.2.2 on 2024-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0024_conversation_point_alter_conversation_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
