# Generated by Django 4.2.2 on 2024-07-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0026_alter_person_media_alter_person_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year of Birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year of Death'),
        ),
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='varosha.person', verbose_name='Father'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='varosha.person', verbose_name='Mother'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name in English'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_gr',
            field=models.CharField(max_length=64, verbose_name='Name in Greek'),
        ),
    ]
