# Generated by Django 4.2.2 on 2024-07-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varosha', '0028_alter_point_name_alter_point_name_gr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name in English'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_gr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name in Greek'),
        ),
    ]
